version: '3.1'
services:
  frontend:
    build: redbicicletas/front
    ports:
      - 3300:3300
    depends_on:
      - crud
  crud:
    build: redbicicletas/crud
    ports:
      - 3000:3000
    volumes:
      - ./bicicletas.db:/app/database/bicicletas.db
    
    
    
